src/account/urls.py
from account import views

from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path

app_name = 'account'

urlpatterns = [
    path('contact-us/', views.ContactUs.as_view(), name='contact-us'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.MyProfile.as_view(), name='profile'),
    path('sign-up/', views.SignUp.as_view(), name='sign-up'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.Activate.as_view(), name='activate'),

]

src/rate/urls.py
from django.urls import path

from rate import views

app_name = 'rate'

urlpatterns = [
    path('list/', views.RateList.as_view(), name='list'),
    path('download-csv/', views.RateDownloadCSV.as_view(), name='download-csv'),
    path('download-xlsx/', views.RateDownloadXLSX.as_view(), name='download-xlsx'),
    path('latest-rates/', views.LatestRatesView.as_view(), name='latest-rates'),
    path('edit/<int:pk>', views.EditRate.as_view(), name='edit'),
    path('delete/<int:pk>', views.DeleteRate.as_view(), name='delete'),
]

src/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from settings import views

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

API_PREFIX = 'api/v1'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('account/', include('account.urls')),
    path('rate/', include('rate.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(f'{API_PREFIX}/rate/', include('rate.api.urls')),
    path(f'{API_PREFIX}/user/', include('account.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(rf'^{API_PREFIX}/swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0),
            name='schema-json'),
    re_path(rf'^{API_PREFIX}/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(rf'^{API_PREFIX}/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = views.handler404
handler500 = views.handler500

src/templates/parts/navbar.html
{% load active_tab %}

<nav class="navbar navbar-dark bg-dark">
	<a class="navbar-brand" href="{% url 'index' %}">Home</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
			aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarText">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item {{ request.path|active:'index' }}">
				<a class="nav-link" href="{% url 'index' %}">Home</a>
			</li>
			<li class="nav-item {{ request.path|active:'rate:list' }}">
				<a class="nav-link" href="{% url 'rate:list' %}">Rates</a>
			</li>
			<li class="nav-item {{ request.path|active:'rate:latest-rates' }}">
				<a class="nav-link" href="{% url 'rate:latest-rates' %}">Latest Rates</a>
			</li>
			<li class="nav-item {{ request.path|active:'account:contact-us' }}">
				<a class="nav-link" href="{% url 'account:contact-us' %}">Contact Us</a>
			</li>
			{% if request.user.is_authenticated %}
				<li class="nav-item {{ request.path|active:'account:profile' }}">
					<a class="nav-link" href="{% url 'account:profile' %}">My Profile</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
				</li>
			{% else %}
				<li class="nav-item {{ request.path|active:'account:sign-up' }}">
					<a class="nav-link" href="{% url 'account:sign-up' %}">Sign Up</a>
				</li>
				<li class="nav-item {{ request.path|active:'account:login' }}">
					<a class="nav-link" href="{% url 'account:login' %}">Login</a>
			{% endif %}
		</ul>
	</div>
</nav>