src/rate/api/urls.py
from django.urls import path

from rate.api import views

app_name = 'api-rate'

urlpatterns = [
    path('rates/', views.RateListCreateView.as_view(), name='rates'),
    path('rates/<int:pk>/', views.RateReadUpdateDeleteView.as_view(), name='rate'),
    path('latest-rates/', views.LatestRatesListView.as_view(), name='latest_rates'),
]

src/rate/urls.py
from django.urls import path

from rate import views

app_name = 'rate'

urlpatterns = [
    path('list/', views.RateList.as_view(), name='list'),
    path('download-csv/', views.RateDownloadCSV.as_view(), name='download-csv'),
    path('download-xlsx/', views.RateDownloadXLSX.as_view(), name='download-xlsx'),
    path('latest-rates/', views.LatestRatesView.as_view(), name='latest-rates'),
    path('edit/<int:pk>', views.EditRate.as_view(), name='edit'),
    path('delete/<int:pk>', views.DeleteRate.as_view(), name='delete'),
]

src/settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework import permissions

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from settings import views

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

API_PREFIX = 'api/v1'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('account/', include('account.urls')),
    path('rate/', include('rate.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(f'{API_PREFIX}/rate/', include('rate.api.urls')),
    path(f'{API_PREFIX}/user/', include('account.api.urls')),
    path(f'{API_PREFIX}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_PREFIX}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(rf'^{API_PREFIX}/swagger(?P<format>\.json|\.yaml)$',
            schema_view.without_ui(cache_timeout=0),
            name='schema-json'),
    re_path(rf'^{API_PREFIX}/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(rf'^{API_PREFIX}/redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = views.handler404
handler500 = views.handler500

src/rate/models.py
from django.db import models
from django.utils import timezone

from rate import model_choices as mch
from rate.utils import to_decimal


tz = timezone.get_default_timezone()


class Rate(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    rate = models.DecimalField(max_digits=7, decimal_places=2)
    source = models.PositiveSmallIntegerField(choices=mch.SOURCE_CHOICES)
    currency_type = models.PositiveSmallIntegerField(choices=mch.CURRENCY_TYPE_CHOICES)
    rate_type = models.PositiveSmallIntegerField(choices=mch.RATE_TYPE_CHOICES)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.rate = to_decimal(self.rate)

    def get_date(self):
        return f'{self.created.astimezone(tz).strftime("%d.%m.%Y %H:%M")}'

src/rate/api/views.py
from django_filters.rest_framework import DjangoFilterBackend

from rate.api.serializers import RateSerializer
from rate.models import Rate
from rate.selectors import get_latest_rates

from rest_framework import generics


class RateListCreateView(generics.ListCreateAPIView):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['rate', 'source', 'currency_type', 'rate_type']


class RateReadUpdateDeleteView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Rate.objects.all()
    serializer_class = RateSerializer


class LatestRatesListView(generics.ListAPIView):
    queryset = get_latest_rates()
    serializer_class = RateSerializer

src/rate/views.py
import csv

from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView, TemplateView, UpdateView, View

from django_filters.views import FilterView

from rate.filters import RateFilter
from rate.models import Rate
from rate.selectors import get_latest_rates
from rate.utils import display

import xlsxwriter


class RateList(FilterView):
    paginate_by = 24
    queryset = Rate.objects.all()
    template_name = 'rate-list.html'
    filterset_class = RateFilter


class RateDownloadCSV(View):
    HEADERS = (
        'id',
        'created',
        'rate',
        'source',
        'currency_type',
        'rate_type',
    )

    queryset = Rate.objects.all().iterator()

    def get(self, request):
        response = self.get_response

        writer = csv.writer(response)
        writer.writerow(self.__class__.HEADERS)

        for rate in self.queryset:

            values = []
            for attr in self.__class__.HEADERS:
                values.append(display(rate, attr))

            writer.writerow(values)
        return response

    @property
    def get_response(self):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="rates.csv"'
        return response


class RateDownloadXLSX(View):
    HEADERS = (
        'id',
        'created',
        'rate',
        'source',
        'currency_type',
        'rate_type',
    )

    queryset = Rate.objects.all()

    def get(self, request):
        response = self.get_response

        book = xlsxwriter.Workbook(response, {'in_memory': True})
        sheet = book.add_worksheet()

        for i, column in enumerate(self.__class__.HEADERS):
            sheet.write(0, i, column)

        for i, rate in enumerate(self.queryset, start=1):
            values = []
            for attr in self.__class__.HEADERS:
                values.append(display(rate, attr))

            for j, value in enumerate(values):
                sheet.write(i, j, value)

        book.close()

        return response

    @property
    def get_response(self):
        response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
        response['Content-Disposition'] = "attachment; filename=rates.xlsx"
        return response


class LatestRatesView(TemplateView):
    template_name = 'latest-rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_latest_rates()
        return context


class EditRate(UserPassesTestMixin, UpdateView):
    template_name = 'edit-rate.html'
    model = Rate
    fields = 'rate', 'source', 'currency_type', 'rate_type'
    success_url = reverse_lazy('rate:list')

    def test_func(self):
        return self.request.user.is_superuser


class DeleteRate(UserPassesTestMixin, DeleteView):
    model = Rate
    success_url = reverse_lazy('rate:list')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def test_func(self):
        return self.request.user.is_superuser

src/rate/templates/edit-rate.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}Edit Rate{% endblock title %}

{% block content %}
	<br><div class="d-flex justify-content-center border border-dark rounded">Rate</div><br>
	<form method="post">
	{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-dark" type="submit">Save</button>
	</form>
{% endblock content %}

src/rate/templates/latest-rates.html
{% extends 'base.html' %}

{% block title %}Latest Rates{% endblock title %}

{% block content %}
    <button type="button" class="btn btn-dark reload-rates-js">
        Reload Rates
    </button>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">id</th>
      <th scope="col">Date</th>
      <th scope="col">Rate</th>
      <th scope="col">Source</th>
      <th scope="col">Currency</th>
      <th scope="col">Rate type</th>
    </tr>
  </thead>

  <tbody>
  {% for rate in object_list %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ rate.id }}</td>
      <td>{{  rate.created }}</td>
      <td>{{  rate.rate }}</td>
      <td>{{ rate.get_source_display }}</td>
      <td>{{ rate.get_currency_type_display }}</td>
      <td>{{ rate.get_rate_type_display }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}

{% block extra_js %}
    <script>
        $(document).ready(function () {
            $("table").click(function () {
                alert('hello');

            // start
            $(".reload-rates-js").click(function () {
                $("tbody tr").remove();
                $.get('/api/v1/rate/latest-rates/').done(function (data) {

                    let i;

                    for (i = 0; i < data.length; i++) {
                        let item = data[i];
                        $('tbody:last-child').append(
                            '<tr>' +
                            '<th>1</th>' +
                            `<td>${item.id}</td>` +
                            `<td>${item.created}</td>` +
                            `<td>${item.get_source_display}</td>` +
                            `<td>${item.amount}</td>` +
                            `<td>${item.get_type_display}</td>` +
                            `<td>${item.get_currency_type_display}</td>` +
                            '</tr>'
                        );
                    }

                });
            });
            // end


        });
    </script>
{% endblock extra_js %}

src/rate/templates/rate-list.html
{% extends 'base.html' %}
{% load pagination %}

{% block title %}Rates{% endblock title %}

{% block content %}
	<br>
	<a href="{% url 'rate:download-csv' %}" class="btn btn-dark btn-lg active" role="button" aria-pressed="true">Download CSV</a>
	<a href="{% url 'rate:download-xlsx' %}" class="btn btn-dark btn-lg active" role="button" aria-pressed="true">Download XLSX</a>
	<br><br>

	<form method="get">
		{{ filter.form.as_p }}
		<button type="submit" class="btn btn-dark">
			<span class="glyphicon glyphicon-search">Search</span>
		</button>
	</form>
	<table class="table">
		<thead class="thead-dark">
		<tr>
			<th scope="col">#</th>
			<th scope="col">id</th>
			<th scope="col">Date</th>
			<th scope="col">Rate</th>
			<th scope="col">Source</th>
			<th scope="col">Currency</th>
			<th scope="col">Rate type</th>
			{% if user.is_superuser %}
				<th scope="col">Edit</th>
				<th scope="col">Delete</th>
			{% endif %}
		</tr>
		</thead>

		<tbody>
			{% for rate in object_list %}
				<tr>
					<th scope="row">{{ forloop.counter0|add:page_obj.start_index }}</th>
					<td>{{ rate.id }}</td>
					<td>{{  rate.created }}</td>
					<td>{{  rate.rate }}</td>
					<td>{{ rate.get_source_display }}</td>
					<td>{{ rate.get_currency_type_display }}</td>
					<td>{{ rate.get_rate_type_display }}</td>
					{% if user.is_superuser %}
						<td><a class="btn btn-dark" href="{% url 'rate:edit' pk=rate.id %}">Edit</a></td>
						<td><a class="btn btn-dark" href="{% url 'rate:delete' pk=rate.id %}">Delete</a></td>
					{% endif %}
				</tr>
			{% endfor %}
	</tbody>
	</table>
	{% if is_paginated %}
		{% pagination page_obj %}
	{% endif %}
{% endblock content %}